---

- hosts: all
  become: true
  tasks:

  - name: update rep index
    apt:
      update_cache: yes	

  - name: install apache2
    apt:
      name: apache2
      state: absent
 
  - name: add php
    apt:
      name: libapache2-mod-php 
      state: absent
